server:
  port: 9000

spring:
  datasource:
    url: jdbc:mysql://112.33.22.155:3306/nic?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    driverClassName: com.mysql.jdbc.Driver
    username: root
    password: Rld@123456

mybatis:
  mapper-locations: classpath*:mapper/*.xml
  type-aliases-package: com.nic.dal.entity

nic:
  card:
    host: http://www.xunaa.cn
    statusUrl: /wxpay/ch_mobile_query.php
    rechargeUrl: /wxpay/ch_mobile_fee_charge.php

