server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://112.33.22.155:3306/nic?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    driverClassName: com.mysql.jdbc.Driver
    username: root
    password: passw0rd

mybatis:
  mapper-locations: classpath*:mapper/*.xml
  type-aliases-package: com.nic.dal.entity